### ISSUE TITLE
Python Module Access

### ISSUE THREAD

**Issue by theNewFlesh** [elastic/elasticsearch-lang-python#28]
It would great if you could implement either:
1) The ability to specify a Python file (that may import other modules) which is executed with the 
     relevant Elasticsearch variables (doc, _doc, _source, etc) instead of a Python expression.  This will
     involve invoking the exec function instead of the eval function.
OR 
2) Python expressions to have access to modules/objects specified outside of the default Python
    environment.  This will likely mean a configuration option specifying a python function for setting up
    the globals dictionary passed to the eval statement.

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#13369
